# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'File.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPlainTextEdit, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1286, 760)
        MainWindow.setMinimumSize(QSize(1286, 760))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.SystemPara = QGroupBox(self.centralwidget)
        self.SystemPara.setObjectName(u"SystemPara")
        self.SystemPara.setGeometry(QRect(470, 40, 581, 191))
        self.SystemPara.setFlat(False)
        self.mag_label = QLabel(self.SystemPara)
        self.mag_label.setObjectName(u"mag_label")
        self.mag_label.setGeometry(QRect(10, 50, 91, 16))
        self.NA_label = QLabel(self.SystemPara)
        self.NA_label.setObjectName(u"NA_label")
        self.NA_label.setGeometry(QRect(10, 80, 91, 16))
        self.NA_label.setToolTipDuration(-1)
        self.pix_size_label = QLabel(self.SystemPara)
        self.pix_size_label.setObjectName(u"pix_size_label")
        self.pix_size_label.setGeometry(QRect(10, 110, 101, 21))
        self.pix_size_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.DataPath_label = QLabel(self.SystemPara)
        self.DataPath_label.setObjectName(u"DataPath_label")
        self.DataPath_label.setGeometry(QRect(10, 20, 91, 16))
        self.upsam_label = QLabel(self.SystemPara)
        self.upsam_label.setObjectName(u"upsam_label")
        self.upsam_label.setGeometry(QRect(250, 50, 91, 16))
        self.DataPath = QLineEdit(self.SystemPara)
        self.DataPath.setObjectName(u"DataPath")
        self.DataPath.setGeometry(QRect(70, 20, 491, 21))
        self.NA_list_label = QLabel(self.SystemPara)
        self.NA_list_label.setObjectName(u"NA_list_label")
        self.NA_list_label.setGeometry(QRect(250, 110, 91, 16))
        self.mag = QLineEdit(self.SystemPara)
        self.mag.setObjectName(u"mag")
        self.mag.setGeometry(QRect(110, 50, 113, 21))
        self.NA = QLineEdit(self.SystemPara)
        self.NA.setObjectName(u"NA")
        self.NA.setGeometry(QRect(110, 80, 113, 21))
        self.pix_size = QLineEdit(self.SystemPara)
        self.pix_size.setObjectName(u"pix_size")
        self.pix_size.setEnabled(True)
        self.pix_size.setGeometry(QRect(110, 110, 113, 21))
        self.upsam = QLineEdit(self.SystemPara)
        self.upsam.setObjectName(u"upsam")
        self.upsam.setGeometry(QRect(340, 50, 113, 21))
        self.NA_list = QLineEdit(self.SystemPara)
        self.NA_list.setObjectName(u"NA_list")
        self.NA_list.setGeometry(QRect(340, 110, 111, 21))
        self.NA_list.setReadOnly(True)
        self.GPU_ID_label = QLabel(self.SystemPara)
        self.GPU_ID_label.setObjectName(u"GPU_ID_label")
        self.GPU_ID_label.setGeometry(QRect(250, 80, 91, 16))
        self.GPU_ID = QLineEdit(self.SystemPara)
        self.GPU_ID.setObjectName(u"GPU_ID")
        self.GPU_ID.setGeometry(QRect(340, 80, 113, 21))
        self.pix_size_unit = QLabel(self.SystemPara)
        self.pix_size_unit.setObjectName(u"pix_size_unit")
        self.pix_size_unit.setGeometry(QRect(10, 120, 101, 21))
        self.pix_size_unit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.filebrowse = QPushButton(self.SystemPara)
        self.filebrowse.setObjectName(u"filebrowse")
        self.filebrowse.setGeometry(QRect(540, 20, 21, 24))
        self.filebrowse.setToolTipDuration(0)
        self.Wavelength = QLabel(self.SystemPara)
        self.Wavelength.setObjectName(u"Wavelength")
        self.Wavelength.setGeometry(QRect(10, 140, 91, 16))
        self.Lambda = QLineEdit(self.SystemPara)
        self.Lambda.setObjectName(u"Lambda")
        self.Lambda.setEnabled(True)
        self.Lambda.setGeometry(QRect(110, 140, 113, 21))
        self.lambda_unit = QLabel(self.SystemPara)
        self.lambda_unit.setObjectName(u"lambda_unit")
        self.lambda_unit.setGeometry(QRect(10, 150, 101, 21))
        self.lambda_unit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.AlgcomboBox = QComboBox(self.SystemPara)
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.setObjectName(u"AlgcomboBox")
        self.AlgcomboBox.setGeometry(QRect(340, 140, 221, 24))
        self.SltAlgorithm_label = QLabel(self.SystemPara)
        self.SltAlgorithm_label.setObjectName(u"SltAlgorithm_label")
        self.SltAlgorithm_label.setGeometry(QRect(250, 140, 91, 16))
        self.MsgBox = QPlainTextEdit(self.centralwidget)
        self.MsgBox.setObjectName(u"MsgBox")
        self.MsgBox.setGeometry(QRect(10, 540, 1031, 141))
        self.MsgBox.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.MsgBox.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.MsgBox.setReadOnly(True)
        self.MsgBox.setOverwriteMode(True)
        self.MsgBox.setTabStopDistance(500.000000000000000)
        self.MsgBox.setCursorWidth(2)
        self.AlgorithmTab = QTabWidget(self.centralwidget)
        self.AlgorithmTab.setObjectName(u"AlgorithmTab")
        self.AlgorithmTab.setGeometry(QRect(470, 250, 581, 271))
        self.GS = QWidget()
        self.GS.setObjectName(u"GS")
        self.alpha = QLabel(self.GS)
        self.alpha.setObjectName(u"alpha")
        self.alpha.setGeometry(QRect(10, 10, 91, 16))
        self.stepsize = QLineEdit(self.GS)
        self.stepsize.setObjectName(u"stepsize")
        self.stepsize.setGeometry(QRect(110, 10, 113, 21))
        self.AlgorithmTab.addTab(self.GS, "")
        self.EPRY = QWidget()
        self.EPRY.setObjectName(u"EPRY")
        self.AlgorithmTab.addTab(self.EPRY, "")
        self.Gauss_Newton = QWidget()
        self.Gauss_Newton.setObjectName(u"Gauss_Newton")
        self.AlgorithmTab.addTab(self.Gauss_Newton, "")
        self.KK = QWidget()
        self.KK.setObjectName(u"KK")
        self.AlgorithmTab.addTab(self.KK, "")
        self.APIC = QWidget()
        self.APIC.setObjectName(u"APIC")
        self.AlgorithmTab.addTab(self.APIC, "")
        self.Future = QWidget()
        self.Future.setObjectName(u"Future")
        self.JoinBox = QLabel(self.Future)
        self.JoinBox.setObjectName(u"JoinBox")
        self.JoinBox.setGeometry(QRect(20, 10, 241, 16))
        self.JoinBox2 = QPlainTextEdit(self.Future)
        self.JoinBox2.setObjectName(u"JoinBox2")
        self.JoinBox2.setGeometry(QRect(20, 40, 351, 64))
        self.JoinBox2.setReadOnly(True)
        self.AlgorithmTab.addTab(self.Future, "")
        self.DataLoadingBox = QGroupBox(self.centralwidget)
        self.DataLoadingBox.setObjectName(u"DataLoadingBox")
        self.DataLoadingBox.setGeometry(QRect(1060, 40, 211, 111))
        self.Display1raw = QPushButton(self.DataLoadingBox)
        self.Display1raw.setObjectName(u"Display1raw")
        self.Display1raw.setGeometry(QRect(10, 50, 191, 24))
        self.Displayallraw = QPushButton(self.DataLoadingBox)
        self.Displayallraw.setObjectName(u"Displayallraw")
        self.Displayallraw.setGeometry(QRect(10, 80, 191, 24))
        self.LoadData = QPushButton(self.DataLoadingBox)
        self.LoadData.setObjectName(u"LoadData")
        self.LoadData.setGeometry(QRect(10, 20, 191, 24))
        self.DisplayImage = QGroupBox(self.centralwidget)
        self.DisplayImage.setObjectName(u"DisplayImage")
        self.DisplayImage.setGeometry(QRect(0, 40, 461, 481))
        self.graphicsView = QGraphicsView(self.DisplayImage)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 20, 441, 441))
        self.graphicsView.setAutoFillBackground(True)
        self.MsgBox_label = QGroupBox(self.centralwidget)
        self.MsgBox_label.setObjectName(u"MsgBox_label")
        self.MsgBox_label.setGeometry(QRect(0, 520, 1051, 171))
        self.Help = QPushButton(self.centralwidget)
        self.Help.setObjectName(u"Help")
        self.Help.setGeometry(QRect(1070, 10, 191, 24))
        self.Acknowledge = QPlainTextEdit(self.centralwidget)
        self.Acknowledge.setObjectName(u"Acknowledge")
        self.Acknowledge.setGeometry(QRect(1070, 630, 191, 51))
        self.Acknowledge.setReadOnly(True)
        self.ClrMsgBox = QPushButton(self.centralwidget)
        self.ClrMsgBox.setObjectName(u"ClrMsgBox")
        self.ClrMsgBox.setGeometry(QRect(840, 540, 191, 24))
        self.Run = QPushButton(self.centralwidget)
        self.Run.setObjectName(u"Run")
        self.Run.setGeometry(QRect(1070, 330, 191, 41))
        self.ROI_Box = QGroupBox(self.centralwidget)
        self.ROI_Box.setObjectName(u"ROI_Box")
        self.ROI_Box.setGeometry(QRect(1060, 150, 211, 171))
        self.PreROISum = QPushButton(self.ROI_Box)
        self.PreROISum.setObjectName(u"PreROISum")
        self.PreROISum.setGeometry(QRect(10, 140, 191, 24))
        self.PreROISig = QPushButton(self.ROI_Box)
        self.PreROISig.setObjectName(u"PreROISig")
        self.PreROISig.setGeometry(QRect(10, 110, 191, 24))
        self.SetROILen = QPushButton(self.ROI_Box)
        self.SetROILen.setObjectName(u"SetROILen")
        self.SetROILen.setGeometry(QRect(10, 20, 191, 24))
        self.ROI_label = QLabel(self.ROI_Box)
        self.ROI_label.setObjectName(u"ROI_label")
        self.ROI_label.setGeometry(QRect(20, 83, 91, 16))
        self.ROI_label.setToolTipDuration(-1)
        self.ROI = QLineEdit(self.ROI_Box)
        self.ROI.setObjectName(u"ROI")
        self.ROI.setGeometry(QRect(52, 80, 141, 21))
        self.ROI_hint = QLabel(self.ROI_Box)
        self.ROI_hint.setObjectName(u"ROI_hint")
        self.ROI_hint.setGeometry(QRect(10, 40, 181, 32))
        self.ROI_hint.setToolTipDuration(-1)
        self.DisplayResGroup = QGroupBox(self.centralwidget)
        self.DisplayResGroup.setObjectName(u"DisplayResGroup")
        self.DisplayResGroup.setGeometry(QRect(1060, 370, 211, 111))
        self.DisplayAmp = QPushButton(self.DisplayResGroup)
        self.DisplayAmp.setObjectName(u"DisplayAmp")
        self.DisplayAmp.setGeometry(QRect(10, 50, 101, 24))
        self.DisplayPupil = QPushButton(self.DisplayResGroup)
        self.DisplayPupil.setObjectName(u"DisplayPupil")
        self.DisplayPupil.setGeometry(QRect(10, 80, 101, 24))
        self.DisplayPhase = QPushButton(self.DisplayResGroup)
        self.DisplayPhase.setObjectName(u"DisplayPhase")
        self.DisplayPhase.setGeometry(QRect(110, 50, 91, 24))
        self.DisplayPupil_2 = QPushButton(self.DisplayResGroup)
        self.DisplayPupil_2.setObjectName(u"DisplayPupil_2")
        self.DisplayPupil_2.setGeometry(QRect(110, 80, 91, 24))
        self.LoadResults_3 = QPushButton(self.DisplayResGroup)
        self.LoadResults_3.setObjectName(u"LoadResults_3")
        self.LoadResults_3.setGeometry(QRect(10, 20, 191, 24))
        self.SaveGroup = QGroupBox(self.centralwidget)
        self.SaveGroup.setObjectName(u"SaveGroup")
        self.SaveGroup.setGeometry(QRect(1060, 480, 211, 80))
        self.LoadResults = QPushButton(self.SaveGroup)
        self.LoadResults.setObjectName(u"LoadResults")
        self.LoadResults.setGeometry(QRect(10, 50, 191, 24))
        self.LoadResults_2 = QPushButton(self.SaveGroup)
        self.LoadResults_2.setObjectName(u"LoadResults_2")
        self.LoadResults_2.setGeometry(QRect(10, 20, 191, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.SaveGroup.raise_()
        self.DisplayResGroup.raise_()
        self.ROI_Box.raise_()
        self.MsgBox_label.raise_()
        self.DisplayImage.raise_()
        self.SystemPara.raise_()
        self.MsgBox.raise_()
        self.AlgorithmTab.raise_()
        self.DataLoadingBox.raise_()
        self.Help.raise_()
        self.Acknowledge.raise_()
        self.ClrMsgBox.raise_()
        self.Run.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1286, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.AlgorithmTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.SystemPara.setTitle(QCoreApplication.translate("MainWindow", u"System parameters", None))
#if QT_CONFIG(tooltip)
        self.mag_label.setToolTip(QCoreApplication.translate("MainWindow", u"System magnifications", None))
#endif // QT_CONFIG(tooltip)
        self.mag_label.setText(QCoreApplication.translate("MainWindow", u"Magnification", None))
#if QT_CONFIG(tooltip)
        self.NA_label.setToolTip(QCoreApplication.translate("MainWindow", u"Numerical Aperture", None))
#endif // QT_CONFIG(tooltip)
        self.NA_label.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.pix_size_label.setText(QCoreApplication.translate("MainWindow", u"Camera pixel size", None))
        self.DataPath_label.setText(QCoreApplication.translate("MainWindow", u"Data Path", None))
        self.upsam_label.setText(QCoreApplication.translate("MainWindow", u"Upsample rate", None))
        self.DataPath.setText(QCoreApplication.translate("MainWindow", u"Enter file path or browse .mat file for input", None))
#if QT_CONFIG(tooltip)
        self.NA_list_label.setToolTip(QCoreApplication.translate("MainWindow", u"Illumination angle list", None))
#endif // QT_CONFIG(tooltip)
        self.NA_list_label.setText(QCoreApplication.translate("MainWindow", u"Angle list", None))
        self.mag.setText(QCoreApplication.translate("MainWindow", u"optional", None))
        self.NA.setText(QCoreApplication.translate("MainWindow", u"optional", None))
        self.pix_size.setText(QCoreApplication.translate("MainWindow", u"optional", None))
        self.upsam.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.NA_list.setText(QCoreApplication.translate("MainWindow", u"(Read Only)", None))
#if QT_CONFIG(tooltip)
        self.GPU_ID_label.setToolTip(QCoreApplication.translate("MainWindow", u"-1 for no GPU, otherwise 0,1,2,3 or ...", None))
#endif // QT_CONFIG(tooltip)
        self.GPU_ID_label.setText(QCoreApplication.translate("MainWindow", u"GPU ID", None))
        self.GPU_ID.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.pix_size_unit.setText(QCoreApplication.translate("MainWindow", u"(um)", None))
        self.filebrowse.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.Wavelength.setToolTip(QCoreApplication.translate("MainWindow", u"Illumination angle list", None))
#endif // QT_CONFIG(tooltip)
        self.Wavelength.setText(QCoreApplication.translate("MainWindow", u"Wavelength", None))
        self.Lambda.setText(QCoreApplication.translate("MainWindow", u"optional", None))
        self.lambda_unit.setText(QCoreApplication.translate("MainWindow", u"(um)", None))
        self.AlgcomboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Gerchberg-Saxton", None))
        self.AlgcomboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"EPRY Embedded pupil function recovery", None))
        self.AlgcomboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Gauss-Newton", None))
        self.AlgcomboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"KK Kramers-Kronig relation", None))
        self.AlgcomboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"APIC Angular Pychographic Imaging with Closed-form method", None))

#if QT_CONFIG(tooltip)
        self.SltAlgorithm_label.setToolTip(QCoreApplication.translate("MainWindow", u"Algorithm selection", None))
#endif // QT_CONFIG(tooltip)
        self.SltAlgorithm_label.setText(QCoreApplication.translate("MainWindow", u"Algorithm", None))
        self.MsgBox.setDocumentTitle("")
        self.MsgBox.setPlainText(QCoreApplication.translate("MainWindow", u"Welcome to Fourier Ptychographic Microscopy reconstruction algorithm software!", None))
#if QT_CONFIG(tooltip)
        self.alpha.setToolTip(QCoreApplication.translate("MainWindow", u"Step size", None))
#endif // QT_CONFIG(tooltip)
        self.alpha.setText(QCoreApplication.translate("MainWindow", u"alpha", None))
        self.stepsize.setText(QCoreApplication.translate("MainWindow", u"1.0", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.GS), QCoreApplication.translate("MainWindow", u"Gerchberg-Saxton", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.EPRY), QCoreApplication.translate("MainWindow", u"EPRY ", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.Gauss_Newton), QCoreApplication.translate("MainWindow", u"Gauss-Newton", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.KK), QCoreApplication.translate("MainWindow", u"KK", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.APIC), QCoreApplication.translate("MainWindow", u"APIC", None))
        self.JoinBox.setText(QCoreApplication.translate("MainWindow", u"More algorithms to be included.", None))
        self.JoinBox2.setPlainText(QCoreApplication.translate("MainWindow", u"If you are interested in contributing to this software. \n"
"Please contact Haowen Zhou.\n"
"https://hwzhou2020.github.io/", None))
        self.AlgorithmTab.setTabText(self.AlgorithmTab.indexOf(self.Future), QCoreApplication.translate("MainWindow", u"...", None))
        self.DataLoadingBox.setTitle(QCoreApplication.translate("MainWindow", u"Data Loading", None))
        self.Display1raw.setText(QCoreApplication.translate("MainWindow", u"Display single raw image", None))
        self.Displayallraw.setText(QCoreApplication.translate("MainWindow", u"Display all raw image", None))
        self.LoadData.setText(QCoreApplication.translate("MainWindow", u"Load data", None))
        self.DisplayImage.setTitle(QCoreApplication.translate("MainWindow", u"Display Image", None))
        self.MsgBox_label.setTitle(QCoreApplication.translate("MainWindow", u"Message Box", None))
        self.Help.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.Acknowledge.setPlainText(QCoreApplication.translate("MainWindow", u"Designed by Haowen Zhou.\n"
"https://hwzhou2020.github.io/\n"
"Caltech Biophotonics Lab\n"
"", None))
        self.ClrMsgBox.setText(QCoreApplication.translate("MainWindow", u"Clear MessageBox", None))
        self.Run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.ROI_Box.setTitle(QCoreApplication.translate("MainWindow", u"Region of Interest", None))
        self.PreROISum.setText(QCoreApplication.translate("MainWindow", u"Preview ROI (Sum)", None))
        self.PreROISig.setText(QCoreApplication.translate("MainWindow", u"Preview ROI (Single)", None))
        self.SetROILen.setText(QCoreApplication.translate("MainWindow", u"Set ROI", None))
#if QT_CONFIG(tooltip)
        self.ROI_label.setToolTip(QCoreApplication.translate("MainWindow", u"Region of Interest, non-negative integers [X-offset, Y-offset, Width, Height]", None))
#endif // QT_CONFIG(tooltip)
        self.ROI_label.setText(QCoreApplication.translate("MainWindow", u"ROI", None))
        self.ROI.setText(QCoreApplication.translate("MainWindow", u"[1,1,256,256]", None))
#if QT_CONFIG(tooltip)
        self.ROI_hint.setToolTip(QCoreApplication.translate("MainWindow", u"Region of Interest, non-negative integers [X-offset, Y-offset, Width, Height]", None))
#endif // QT_CONFIG(tooltip)
        self.ROI_hint.setText(QCoreApplication.translate("MainWindow", u"Hint: Double click yellow box for\n"
"setting ROI or set values below.", None))
        self.DisplayResGroup.setTitle(QCoreApplication.translate("MainWindow", u"Display Results'", None))
        self.DisplayAmp.setText(QCoreApplication.translate("MainWindow", u"Image Amplitude ", None))
        self.DisplayPupil.setText(QCoreApplication.translate("MainWindow", u"Pupil Amplitude", None))
        self.DisplayPhase.setText(QCoreApplication.translate("MainWindow", u"Image Phase", None))
        self.DisplayPupil_2.setText(QCoreApplication.translate("MainWindow", u"Pupil Phase", None))
        self.LoadResults_3.setText(QCoreApplication.translate("MainWindow", u"Show all", None))
        self.SaveGroup.setTitle(QCoreApplication.translate("MainWindow", u"Save", None))
        self.LoadResults.setText(QCoreApplication.translate("MainWindow", u"Load Results", None))
        self.LoadResults_2.setText(QCoreApplication.translate("MainWindow", u"Save Results", None))
    # retranslateUi

