# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SystemSpecsWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)

class Ui_SystemSpecsWindow(object):
    def setupUi(self, SystemSpecsWindow):
        if not SystemSpecsWindow.objectName():
            SystemSpecsWindow.setObjectName(u"SystemSpecsWindow")
        SystemSpecsWindow.resize(620, 240)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SystemSpecsWindow.sizePolicy().hasHeightForWidth())
        SystemSpecsWindow.setSizePolicy(sizePolicy)
        self.SystemPara = QGroupBox(SystemSpecsWindow)
        self.SystemPara.setObjectName(u"SystemPara")
        self.SystemPara.setGeometry(QRect(20, 20, 581, 201))
        self.SystemPara.setFlat(False)
        self.mag_label = QLabel(self.SystemPara)
        self.mag_label.setObjectName(u"mag_label")
        self.mag_label.setGeometry(QRect(10, 30, 91, 16))
        self.NA_label = QLabel(self.SystemPara)
        self.NA_label.setObjectName(u"NA_label")
        self.NA_label.setGeometry(QRect(10, 60, 91, 16))
        self.NA_label.setToolTipDuration(-1)
        self.pix_size_label = QLabel(self.SystemPara)
        self.pix_size_label.setObjectName(u"pix_size_label")
        self.pix_size_label.setGeometry(QRect(10, 90, 101, 21))
        self.pix_size_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.upsam_label = QLabel(self.SystemPara)
        self.upsam_label.setObjectName(u"upsam_label")
        self.upsam_label.setGeometry(QRect(250, 30, 91, 16))
        self.NA_list_label = QLabel(self.SystemPara)
        self.NA_list_label.setObjectName(u"NA_list_label")
        self.NA_list_label.setGeometry(QRect(250, 90, 91, 16))
        self.mag = QLineEdit(self.SystemPara)
        self.mag.setObjectName(u"mag")
        self.mag.setGeometry(QRect(110, 30, 113, 21))
        self.NA = QLineEdit(self.SystemPara)
        self.NA.setObjectName(u"NA")
        self.NA.setGeometry(QRect(110, 60, 113, 21))
        self.pix_size = QLineEdit(self.SystemPara)
        self.pix_size.setObjectName(u"pix_size")
        self.pix_size.setEnabled(True)
        self.pix_size.setGeometry(QRect(110, 90, 113, 21))
        self.upsam = QLineEdit(self.SystemPara)
        self.upsam.setObjectName(u"upsam")
        self.upsam.setGeometry(QRect(340, 30, 113, 21))
        self.NA_list = QLineEdit(self.SystemPara)
        self.NA_list.setObjectName(u"NA_list")
        self.NA_list.setGeometry(QRect(340, 90, 111, 21))
        self.NA_list.setReadOnly(True)
        self.GPU_ID_label = QLabel(self.SystemPara)
        self.GPU_ID_label.setObjectName(u"GPU_ID_label")
        self.GPU_ID_label.setGeometry(QRect(250, 60, 91, 16))
        self.GPU_ID = QLineEdit(self.SystemPara)
        self.GPU_ID.setObjectName(u"GPU_ID")
        self.GPU_ID.setGeometry(QRect(340, 60, 113, 21))
        self.pix_size_unit = QLabel(self.SystemPara)
        self.pix_size_unit.setObjectName(u"pix_size_unit")
        self.pix_size_unit.setGeometry(QRect(10, 100, 101, 21))
        self.pix_size_unit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Wavelength = QLabel(self.SystemPara)
        self.Wavelength.setObjectName(u"Wavelength")
        self.Wavelength.setGeometry(QRect(10, 120, 91, 16))
        self.Lambda = QLineEdit(self.SystemPara)
        self.Lambda.setObjectName(u"Lambda")
        self.Lambda.setEnabled(True)
        self.Lambda.setGeometry(QRect(110, 120, 113, 21))
        self.lambda_unit = QLabel(self.SystemPara)
        self.lambda_unit.setObjectName(u"lambda_unit")
        self.lambda_unit.setGeometry(QRect(10, 130, 101, 21))
        self.lambda_unit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.AlgcomboBox = QComboBox(self.SystemPara)
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.addItem("")
        self.AlgcomboBox.setObjectName(u"AlgcomboBox")
        self.AlgcomboBox.setGeometry(QRect(340, 120, 221, 24))
        self.SltAlgorithm_label = QLabel(self.SystemPara)
        self.SltAlgorithm_label.setObjectName(u"SltAlgorithm_label")
        self.SltAlgorithm_label.setGeometry(QRect(250, 120, 91, 16))
        self.Cfm_sys_butt = QPushButton(self.SystemPara)
        self.Cfm_sys_butt.setObjectName(u"Cfm_sys_butt")
        self.Cfm_sys_butt.setGeometry(QRect(500, 170, 75, 24))
        self.ROI_slt_label = QLabel(self.SystemPara)
        self.ROI_slt_label.setObjectName(u"ROI_slt_label")
        self.ROI_slt_label.setGeometry(QRect(10, 170, 91, 16))
        self.ROIsltbox = QLineEdit(self.SystemPara)
        self.ROIsltbox.setObjectName(u"ROIsltbox")
        self.ROIsltbox.setEnabled(True)
        self.ROIsltbox.setGeometry(QRect(110, 170, 231, 21))

        self.retranslateUi(SystemSpecsWindow)

        QMetaObject.connectSlotsByName(SystemSpecsWindow)
    # setupUi

    def retranslateUi(self, SystemSpecsWindow):
        SystemSpecsWindow.setWindowTitle(QCoreApplication.translate("SystemSpecsWindow", u"Form", None))
        self.SystemPara.setTitle(QCoreApplication.translate("SystemSpecsWindow", u"System parameters", None))
#if QT_CONFIG(tooltip)
        self.mag_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"System magnifications", None))
#endif // QT_CONFIG(tooltip)
        self.mag_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"Magnification", None))
#if QT_CONFIG(tooltip)
        self.NA_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"Numerical Aperture", None))
#endif // QT_CONFIG(tooltip)
        self.NA_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"NA", None))
        self.pix_size_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"Camera pixel size", None))
        self.upsam_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"Upsample rate", None))
#if QT_CONFIG(tooltip)
        self.NA_list_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"Illumination angle list", None))
#endif // QT_CONFIG(tooltip)
        self.NA_list_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"Angle list", None))
        self.mag.setText(QCoreApplication.translate("SystemSpecsWindow", u"optional", None))
        self.NA.setText(QCoreApplication.translate("SystemSpecsWindow", u"optional", None))
        self.pix_size.setText(QCoreApplication.translate("SystemSpecsWindow", u"optional", None))
        self.upsam.setText(QCoreApplication.translate("SystemSpecsWindow", u"3", None))
        self.NA_list.setText(QCoreApplication.translate("SystemSpecsWindow", u"(Read Only)", None))
#if QT_CONFIG(tooltip)
        self.GPU_ID_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"-1 for no GPU, otherwise 0,1,2,3 or ...", None))
#endif // QT_CONFIG(tooltip)
        self.GPU_ID_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"GPU ID", None))
        self.GPU_ID.setText(QCoreApplication.translate("SystemSpecsWindow", u"-1", None))
        self.pix_size_unit.setText(QCoreApplication.translate("SystemSpecsWindow", u"(um)", None))
#if QT_CONFIG(tooltip)
        self.Wavelength.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"Illumination angle list", None))
#endif // QT_CONFIG(tooltip)
        self.Wavelength.setText(QCoreApplication.translate("SystemSpecsWindow", u"Wavelength", None))
        self.Lambda.setText(QCoreApplication.translate("SystemSpecsWindow", u"optional", None))
        self.lambda_unit.setText(QCoreApplication.translate("SystemSpecsWindow", u"(um)", None))
        self.AlgcomboBox.setItemText(0, QCoreApplication.translate("SystemSpecsWindow", u"Gerchberg-Saxton", None))
        self.AlgcomboBox.setItemText(1, QCoreApplication.translate("SystemSpecsWindow", u"EPRY Embedded pupil function recovery", None))
        self.AlgcomboBox.setItemText(2, QCoreApplication.translate("SystemSpecsWindow", u"Gauss-Newton", None))
        self.AlgcomboBox.setItemText(3, QCoreApplication.translate("SystemSpecsWindow", u"KK Kramers-Kronig relation", None))
        self.AlgcomboBox.setItemText(4, QCoreApplication.translate("SystemSpecsWindow", u"APIC Angular Pychographic Imaging with Closed-form method", None))

#if QT_CONFIG(tooltip)
        self.SltAlgorithm_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"Algorithm selection", None))
#endif // QT_CONFIG(tooltip)
        self.SltAlgorithm_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"Algorithm", None))
        self.Cfm_sys_butt.setText(QCoreApplication.translate("SystemSpecsWindow", u"Confirm", None))
#if QT_CONFIG(tooltip)
        self.ROI_slt_label.setToolTip(QCoreApplication.translate("SystemSpecsWindow", u"Algorithm selection", None))
#endif // QT_CONFIG(tooltip)
        self.ROI_slt_label.setText(QCoreApplication.translate("SystemSpecsWindow", u"ROI selection", None))
        self.ROIsltbox.setText(QCoreApplication.translate("SystemSpecsWindow", u"[1,1,256,256]", None))
    # retranslateUi

