name: fpm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pyside6
  - pyyaml
  - pytorch
  - matplotlib
  - h5py
  - pip
  - pip:
    - mat73
    - opencv-python
    - imageio
    - scikit-image
    - tqdm
    - sphinx_rtd_theme